let suggestions = [
    "Osman",
    "KodcuAhmet",
    "Recep",
    "Berkay",
    "Coding",
    "Recep tayyip erdogan",
    "Mustafa killibaak",
    "Getir",
    "Yemeksepeti",
    "Freelancer",
    "Youtube",
    "How to become a millionare",
    "Web Developer",
    "Nasil Zengin oluruz",
    "Login Form",
    "Facebook",
    "Cumhur ittifaki",
    "Millet ittifaki",
]